### ISSUE TITLE
Question: How are you packing the executables?

### ISSUE THREAD

**Issue by irishgreencitrus** [hiulit/Unofficial-Godot-Engine-Raspberry-Pi#10]
Are you just stripping the binaries and zipping them? Or are you doing something else as well?

**Comment by hiulit** [comment]
I'm stripping them and them zipping them.

**Comment by hiulit** [comment]
I'm also packing them like this:

<img width="606" alt="Captura de Pantalla 2021-06-07 a les 15 22 38" src="https://user-images.githubusercontent.com/481475/121024247-5506b900-c7a4-11eb-9470-0538fa1ff3bf.png">

But that's something that I could do myself. You don't have to bother ;)

**Comment by irishgreencitrus** [comment]
Ah ok. I was going to suggest using UPX, as it decreases the file size further https://upx.github.io/

**Comment by irishgreencitrus** [comment]
Actually UPX doesn't work for Godot binaries correctly

**Comment by hiulit** [comment]
I didn't know about UPX. I just followed what the main developers do :)

**Comment by irishgreencitrus** [comment]
UPX breaks the export templates, so it's not worth using.
