### ISSUE TITLE
Installing Export Templates

### ISSUE THREAD

**Issue by gururise** [hiulit/Unofficial-Godot-Engine-Raspberry-Pi#13]
Sorry if this is explained somewhere, but I wasn't able to find any clarification as to what the including export template binaries are for.  When I go to "Manage Exports" I am able to download the "official" export templates for Godot 3.3.2.  

I am unable to import the export template included in the zip file.  If we wish to export to raspberry pi, should we be using the included export template?  If so, how does one install it?

**Comment by timvisee** [comment]
See: https://github.com/hiulit/Unofficial-Godot-Engine-Raspberry-Pi#-how-to-export-a-game-using-the-export-templates

**Comment by hiulit** [comment]
Thank you @timvisee .

@gururise You won't he Raspberry Pi export templates in the official templates. You have to follow the instructions @timvisee mentioned. Feel free to reopen the issue if you find any issue,
