### ISSUE TITLE
Can't run binaries in a VM

### ISSUE THREAD

**Issue by ragreenburg** [hiulit/Unofficial-Godot-Engine-Raspberry-Pi#15]
I am trying to help my brother install Godot on a Raspberry Pi 400 I got him and part of that has been trying to install stuff in a raspbian VM so I can figure out how to get everything to work before having him try.

When I unzip the binaries and run both the raspberry pi 3 and 4 versions and run `./godot_3.3.3-stable_rpiX_editor_lto.bin` I just get `/lib/ld-linux-armhf.so.3: No such file or directory`.

**Comment by ragreenburg** [comment]
Shoot, I figured it would be something like that. Thanks for the info!

**Comment by hiulit** [comment]
No worries! Glad to help ;)

You should try to install everything directly on the Pi instead of a VM though. Some packages might not work for ARM.

**Comment by ragreenburg** [comment]
You're definitely right but I unfortunately don't have physical access to it and can't SSH into it from work.
