### ISSUE TITLE
Interest in building each public release dating back to 2016?

### ISSUE THREAD

**Issue by stevepdp** [hiulit/Unofficial-Godot-Engine-Raspberry-Pi#19]
Firstly, many thanks for this project and documenting how to compile the engine and tools on a Raspberry Pi. I found myself needing to test Godot version 2.1.4 on a Raspberry Pi 400 and I was able to build it on Buster from the df70d283d8 commit with success.

Given that there are [36 stable releases](https://downloads.tuxfamily.org/godotengine/) of Godot at the time of writing this, I'm wondering whether it's worthwhile building the other stable versions of the project for this target? The value would be in the ease of opening any _existing_ Godot project. Anything to lessen the work of bringing existing games across seems like a good thing to do.

I'm willing to try this with my Pi 400 as I believe in it's potential as a console / A600-like. I'm not sure however if it's something you would welcome into this repo or whether it's something I should pursue independently?

Let me know what you think?

**Comment by stevepdp** [comment]
I've shared my build steps [here](https://gist.github.com/stevepdp/18b8d2c4f18e051672ae98e7051a7724) incase they help anyone. There's some extra info regarding the OS, Python environment, compile flags etc.

**Comment by irishgreencitrus** [comment]
I think it would be helpful to play all games on itch.io (or other places) that distribute the `.pck` file. It's quite hard to compile them all, as the older versions use older compilation tools (older versions of `scons`, `python2` as well as older versions of `gcc`). I'm going to have a look at making some `Dockerfile`s, as that would help with reproducibility.

**Comment by hiulit** [comment]
That's what I use for the [Retropie Godot Engine Emulator](https://github.com/hiulit/RetroPie-Godot-Engine-Emulator). I have the latest stable release of each version and I open the pck file.
I've [tested a lot of games](https://docs.google.com/spreadsheets/d/1ybU_NHqhnJmZnlP9YDDGEf4BJ5nInbfsVVQtQCM7rYw/edit#gid=0) on itch.io, most games work fine.
