### ISSUE TITLE
Server builds?

### ISSUE THREAD

**Issue by irishgreencitrus** [hiulit/Unofficial-Godot-Engine-Raspberry-Pi#2]
Would it be possible to use one of these as a server?
I think it'd be best to get a dedicated server build as it would not require a desktop environment or even a graphics driver

**Comment by hiulit** [comment]
I'm sorry, I'm not familiar with "server builds". What are those? What are they used for?

**Comment by irishgreencitrus** [comment]
A server build is a binary which is commonly used to run dedicated servers and doesn't require a graphics driver. I've built one myself, and it runs surprisingly well and can easily handle 10-20 players (but that of course depends on your game). These are the scons arguments I used. 
`scons platform=server target=release tools=no use_llvm=yes CCFLAGS="-mtune=cortex-a72 -mcpu=cortex-a72 -mfloat-abi=hard -mlittle-endian -munaligned-access -mfpu=neon-fp-armv8" -j4`
[Godot docs on dedicated servers](https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_dedicated_servers.html)
[Godot docs on compiling dedicated server builds](https://docs.godotengine.org/en/stable/development/compiling/compiling_for_x11.html#compiling-a-headless-server-build)

**Comment by hiulit** [comment]
OK, I see.
To clarify then, you suggest that I compile server builds to distribute in this repo besides the one I already have?

**Comment by irishgreencitrus** [comment]
Yes, basically. I think it'd be useful for testing network multiplayer or even running small games off of it. (BTW, they aren't export templates, you build it and run it with a main .pck file)

**Comment by hiulit** [comment]
I'm compiling both headless and server builds right now ;)

**Comment by irishgreencitrus** [comment]
Cheers!

**Comment by hiulit** [comment]
Do you think I could `strip` the server build? Like I do with my export templates?

**Comment by irishgreencitrus** [comment]
Don't know what that is sorry

**Comment by hiulit** [comment]
This https://docs.godotengine.org/en/stable/development/compiling/optimizing_for_size.html#stripping-binaries
And yes, we can :)

**Comment by hiulit** [comment]
Headless and server builds are up! ;)

**Comment by irishgreencitrus** [comment]
Guess thats the issue over then. Thanks for doing this again!

**Comment by hiulit** [comment]
No problem. Let me know if the builds work if you ever try one :)

**Comment by irishgreencitrus** [comment]
Just tried a 3.2.3 build and it says `no file or directory` when running. Output of file command makes it seem like one is 32bit and the other 64bit. I was running on 64bit ubuntu server 20.10 but I assume they will work on 32bit pi os. If you think this warrants a reopen do so but I think majority of people will be using raspberry pi os, so maybe not relevant?

**Comment by hiulit** [comment]
I don't understand the error. I just tried running both the headless and the server 3.2.3 builds and they work fine.

Do you think, or are you suggesting that because my builds are 32 bits they won't work work on a 64 bits environment? They should, shouldn't they?

Or is it because Ubuntu Server 20.10 doesn't have 32 bit support?

If that's the case I don't think I can do anything about it because I'm compiling on Raspberry Pi OS 32 bits. Maybe I could give the Raspberry Pi OS 64 bits a try so I could compile 32c and 64 bits builds, but it's beta, so I would wait until it's out of beta.

**Comment by irishgreencitrus** [comment]
If you want i could compile the 64 bit builds and send them your way. Yeah ubuntu server doesn't have 32 bit support for some reason even though it is supported on the board.

**Comment by hiulit** [comment]
Yeah, sure! Thanks, that would be great :)
Do you think if they are compiled on Ubuntu Server 20.10 they will work on Raspberry Pi OS?

**Comment by irishgreencitrus** [comment]
I don't see why not, but I can always check. Raspberry Pi OS is based on ubuntu and they'd both be 64bit. Is there anywhere I can send them once done?

**Comment by hiulit** [comment]
Maybe a WeTransfer or something like that? Because they won't fit in an email I think. Or if you have Google Drive or the like, you could upload them there and I'll downloaded them from there.

**Comment by irishgreencitrus** [comment]
@hiulit https://drive.google.com/file/d/13DTSTxtzT_8vBfZRQHwYBq2_LLZKkjJt/view?usp=sharing

**Comment by hiulit** [comment]
Hey! Thank you @irishgreencitrus :) I'll add them when I have the time

**Comment by hiulit** [comment]
BTW @irishgreencitrus did you strip the binaries? Because I think their could be smaller by stripping the debug symbols. Simply run `strip binary_name.llvm` and you should see how its size gets smaller.

**Comment by irishgreencitrus** [comment]
I'm not sure. I think i might of done. I'm currently working on a tool to do all of this automatically. Check out [this](https://github.com/irishgreencitrus/godot-build-cli-go) Shameless I know.
