### ISSUE TITLE
Video support not working - pi 4 & 3

### ISSUE THREAD

**Issue by Edwardphantom** [hiulit/Unofficial-Godot-Engine-Raspberry-Pi#20]
hello, i trying to do an small app that play videos on raspberry pi, but the game can´t load or work with videos , giving me these errors : 
![unknown](https://user-images.githubusercontent.com/26088809/151185996-210dc302-7b62-421c-a79d-b20af8f5e46d.png)
 
same error, webm or ogv 

if requested, i can upload the concept test project, it´s small ( just 55 MB) 

all the project are doing with VisualScripting

of course, this error occurs only using the export template binary

**Comment by hiulit** [comment]
Hey, sorry for the late reply! Yeah, it won't work.
The Theora and WebM modules are disabled because I couldn't compile for the Pi with those modules enabled.

**Comment by daniel-sanche** [comment]
For others who run into this limitation: You can use the godot videoplayer on the raspberry pi through [FRT](https://github.com/efornara/frt). 

You'll just have to export the project on a different machine using an official build of Godot
