### ISSUE TITLE
3.4.4 Editor Issues

### ISSUE THREAD

**Issue by ArmsTheLimited** [hiulit/Unofficial-Godot-Engine-Raspberry-Pi#22]
Hi! I'm trying to run the 3.4.4 editor on an arm64 Raspberry Pi 4. I downloaded the correct version, and launched the project manager, which went perfectly when creating a project and running asset library projects from godotengine.org. However,  after I've edited an existing project and I run it, I get repeated `DRM_IOCTL_MODE_CREATE_DUMB failed: Cannot allocate memory
Failed to create scanout resource
` in the terminal, and the godot window seems to be transparent after that. I have to kill the process and restart it to access the editor.

Thanks in advance

**Comment by hiulit** [comment]
I'm so sorry, but I don't have any idea about what could be happening.
As they say on this industry: "It works on my machine", hehe! :)
A part from the bad joke, a quick search on the Internet gave me the idea that it might be something to do with the OS. Could you try a clean install and see if it still happens?

**Comment by ArmsTheLimited** [comment]
Thanks! I did a clean install and it works now, along with a myriad of other apps that had the same issue.
