### ISSUE TITLE
64 bit version for Raspi 3

### ISSUE THREAD

**Issue by k5nn** [hiulit/Unofficial-Godot-Engine-Raspberry-Pi#27]
Hello I noticed that the binaries for Raspberry Pi are in 32 bit would like to know what it would take to compile it into 64 bit

Currently on raspi 3B

**Comment by hiulit** [comment]
Hi there! I don't have a toolchain to compile 64 bits binaries for the Pi3.
The 64 bits are compiled on a Pi4. These might work on a Pi3 with a 64 bit OS. Give it a try and let me know.

**Comment by k5nn** [comment]
Hello yes it's working probably should update the readme.md

**Comment by hiulit** [comment]
Nice! Thank you for giving it a try :)
I'll update the README accordingly.
