### ISSUE TITLE
OpenGL Error with GLES2 on PI400

### ISSUE THREAD

**Issue by procfxgen** [hiulit/Unofficial-Godot-Engine-Raspberry-Pi#3]
Hi, thanks a lot for the Godot PI4 version :-)
But I have an error when I launch "2D physics Patformer demo" (with GLES2 forced)
Unable to initialize Video Driver ....
Thanks.

Running: /home/pi/Downloads/godot_3.2.3_rpi4_editor.bin --path /home/pi/godot_demos/2D%20Physics%20Platformer%20Demo%20(RigidBody) --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 6665 --position 240,272
Godot Engine v3.2.3.stable.custom_build.31d0f8ad8 - https://godotengine.org
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  28
  Current serial number in output stream:  25
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  28
  Current serial number in output stream:  25
ERROR: initialize: Condition "ctxErrorOccurred || !p->glx_context" is true. Returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:190.
ERROR: is_viable: Error initializing GLAD
   At: drivers/gles3/rasterizer_gles3.cpp:141.

**Comment by hiulit** [comment]
The project itself is set to GLES3.

Try going to:

- "Project"
- "Project Settings"
- "Quality"
- "Driver Name" and set it to GLES2.

**Comment by hiulit** [comment]
Feel free to reopen the issue it my solution doesn't work.
