### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by The-Sapphire-Starship** [hiulit/Unofficial-Godot-Engine-Raspberry-Pi#5]
Im trying to use the command that you provide for compiling the editor: 

  scons platform=x11 target=release_debug tools=yes use_llvm=yes CCFLAGS="-mtune=cortex-a72 -mcpu=cortex-a72 -mfloat- abi=hard -mlittle-endian -munaligned-access -mfpu=neon-fp-armv8" -j4

but when i try to run it inside of my folder that contains the cloned godot github repo i just get this error:

  bash: scons: command not found

I have a feeling it is something simple that im getting wrong but im new and inexperienced with the command line and i can not figure out how to fix it

**Comment by hiulit** [comment]
You have to install SCons and other dependencies in order to compile Godot. See https://docs.godotengine.org/en/latest/development/compiling/compiling_for_linuxbsd.html
