### ISSUE TITLE
Raspberry PI OS 64bit

### ISSUE THREAD

**Issue by kingcrowley** [hiulit/Unofficial-Godot-Engine-Raspberry-Pi#6]
Hi,

I can't get Godot IDE 3.2.4 RC 1 to run on Raspberry PI OS 64bit see output from Terminal below. To me it looks like it is trying to use libXcursor1 which doesn't exist but I do have libxcursor1 (no capital X) installed 

```
pi@raspberrypi:~/Desktop/godot_3.2.4.rc.1_rpi4_editor $ ./godot_3.2.4.rc.1_rpi4_editor.bin
./godot_3.2.4.rc.1_rpi4_editor.bin: error while loading shared libraries: libXcursor.so.1: cannot open shared object file: No such file or directory
```

`pi@raspberrypi:~/Desktop/godot_3.2.4.rc.1_rpi4_editor $ sudo chmod +x godot_3.2.4.rc.1_rpi4_editor.bin `

No errors
Tried running again same error
```
pi@raspberrypi:~/Desktop/godot_3.2.4.rc.1_rpi4_editor $ sudo apt install -y libXcursor1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libXcursor1
```

So i checked without the capital x and there is a package and i have the latest version. 

```
pi@raspberrypi:~/Desktop/godot_3.2.4.rc.1_rpi4_editor $ sudo apt install -y libxcursor1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libxcursor1 is already the newest version (1:1.1.15-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~/Desktop/godot_3.2.4.rc.1_rpi4_editor $ 
```

**Comment by hiulit** [comment]
It seems that you have to install the 32bit verison of `libcursor1`.

Try this: `sudo apt-get install libxcursor1:i386`
From https://unix.stackexchange.com/questions/110263/how-do-i-install-libxcursor-so-1-on-debian#comment344579_110267

Or this: `sudo apt-get install libxcursor-dev:i386`
From https://github.com/godotengine/godot/issues/3129#issuecomment-166975208

**Comment by kingcrowley** [comment]
I had to run 
`sudo dpkg --add-architecture i386`
First to allow me to get the i386 packaged.
Installed 
`libxcursor1:i386 is already the newest version (1:1.1.15-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

But still have the same issue - could it be trying to use the 64bit version instead of the 32bit?  and Thanks!

**Comment by hiulit** [comment]
I don't know. Maybe @irishgreencitrus can help you.

**Comment by irishgreencitrus** [comment]
i can build it with my tool quite easily [here](https://github.com/irishgreencitrus/godot-build-cli-go). Could you try that for me and i'll see if it works. I compiled the 64bit version in ubuntu server 20.10 originally and i've recently compiled them in manjaro arm64 minimal too.

**Comment by irishgreencitrus** [comment]
Just to make sure can you build server/headless builds or is it just the Godot IDE/ export templates that are having issues?

**Comment by kingcrowley** [comment]
HI - installed your tool (thanks) - followed your instructions and downloaded and tried to build 3.2.3 see below. 

```
download 3.2.3-stable
Downloading 3.2.3-stable.zip
Unzipping 3.2.3-stable.zip
Successfully Unzipped 3.2.3-stable.zip
> build 3.2.3-stable
Building 3.2.3-stable
scons: Reading SConscript files ...
Automatically detected platform: x11
Couldn't parse CXX environment variable to infer compiler version.
Enabling ALSA
Enabling PulseAudio
Couldn't parse CXX environment variable to infer compiler version.
Checking for C header file mntent.h... no
scons: done reading SConscript files.
scons: Building targets ...
run(["core/method_bind.gen.inc", "core/method_bind_ext.gen.inc", "core/method_bind_free_func.gen.inc"], ["core/make_binders.py"])
build_gles3_headers(["drivers/gles3/shaders/exposure.glsl.gen.h"], ["drivers/gles3/shaders/exposure.glsl"])
build_gles3_headers(["drivers/gles3/shaders/resolve.glsl.gen.h"], ["drivers/gles3/shaders/resolve.glsl"])
build_gles3_headers(["drivers/gles3/shaders/scene.glsl.gen.h"], ["drivers/gles3/shaders/scene.glsl"])
Compiling ==> platform/x11/godot_x11.cpp
Compiling ==> platform/x11/crash_handler_x11.cpp
scons: building terminated because of errors.
sh: 1: clang++: not found
scons: *** [platform/x11/godot_x11.x11.tools.64.llvm.o] Error 127
sh: 1: clang++: not found
scons: *** [platform/x11/crash_handler_x11.x11.tools.64.llvm.o] Error 127
```

**Comment by irishgreencitrus** [comment]
you don't have clang installed.
install everything required [here](https://docs.godotengine.org/en/stable/development/compiling/compiling_for_x11.html#distro-specific-one-liners) as well as clang
`sudo apt install clang`

**Comment by kingcrowley** [comment]
Thanks - I posted that and then coped on to that. Installed now and hopefully compiling now

**Comment by irishgreencitrus** [comment]
> Thanks - I posted that and then coped on to that. Installed now and hopefully compiling now.
> 
> Update have 3.2.3 running. Thanks!

yay! my most recent commit makes it even easier to build and download godot, so give the repo a star if u want to see more updates. thanks for using my tool!

**Comment by kingcrowley** [comment]
As an update before I close this - I have built 3.2.4rc4 and looks to be working ok on Raspberry PI OS 64Bit. Thanks for the help.
