### ISSUE TITLE
Update to Godot 3.3

### ISSUE THREAD

**Issue by frankhale** [hiulit/Unofficial-Godot-Engine-Raspberry-Pi#7]
I'm sure you are aware of the release yesterday of Godot 3.3. Just seeing if a build for the Pi is on the horizon? Thank you!!!

https://godotengine.org/article/godot-3-3-has-arrived

**Comment by hiulit** [comment]
Yes, I'm aware of it! I'll compile it when I have the time. 3.3 should perform really nice on the Pi 4 :)

**Comment by frankhale** [comment]
@hiulit thank you! I am loving Godot 3.3.

**Comment by frankhale** [comment]
I just saw the 3.3 update. Thank you! Have a great weekend.

**Comment by hiulit** [comment]
Hehe! You are quick ;) Have a great weekend too

El dv., 23 d’abr. 2021, 16:28, Frank Hale ***@***.***> va
escriure:
