### ISSUE TITLE
Not working on Raspberry Pi 1 - "illegal instruction" error 

### ISSUE THREAD

**Issue by KoxaKoxama** [hiulit/Unofficial-Godot-Engine-Raspberry-Pi#9]
Running editor or any build with export templates for rpi1 I get "illegal instruction", is this was build with ARMv7? RPi1 uses ARMv6 so maybe this is the cause of "illegal instruction" error?

**Comment by hiulit** [comment]
Hi, I'm sorry but I don't have a Pi 1 to test. I use this [other tool](https://github.com/hiulit/cross-compile-godot-raspberry-pi) of mine to compile the binaries for the Pi.
You can take a look at the code to see the flags I used to compile for the different Pi revisions. In particular, for the Pi 1 I use `CCFLAGS="-mcpu=arm1176jzf-s -mtune=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard -mlittle-endian -munaligned-access"`, which I found after much researching to be the ones needed for it.
I'm sorry I can't offer you any solution.

**Comment by hiulit** [comment]
OK, I took a look at the toolchain I'm using to cross-compile binaries and I think it only compiles for ARMv7 (Raspberry Pi 3,4) so even though I pass flags to compile for ARMv6 the toolchain dones't have the tools to do it so it fallbacks to ARMv7.

**Comment by hiulit** [comment]
I removed the links to versions 0, 1 and 2 and the binaries don't work
